### PR TITLE
Readme FAQ

### LINKED ISSUE #23: Usage of id type of Null
Following the readme, I wanted to work with a table that has not `id`. Therefore, I tried to instantiate a `Repo[MyTableCreator, MyTable, Null]`, but I got two compile errors:

First, missing an implicit `ClassTag[Null]`:
```
[error]    |    /* missing */summon[scala.reflect.ClassTag[Null]])
[error]    |
[error]    |But no implicit values were found that match type scala.reflect.ClassTag[Null]
[error]    |
[error]    |where:    derived$DbCodec  is a given instance in object Creator
[error]    |          derived$DbCodec² is a given instance in object Foo
[error]    |          magnum           is a package in package com.augustnagro
[error]    |          magnum²          is a package in package kicks.db
```

Then a missing `DbCodec[Null]` (we can maybe improve the error message in the future):
```
[error]    |java.util.NoSuchElementException: None.get
[error]    |	at scala.None$.get(Option.scala:627)
[error]    |	at scala.None$.get(Option.scala:626)
[error]    |	at com.augustnagro.magnum.RepoDefaults$.genImpl(RepoDefaults.scala:47)
[error]    |	at com.augustnagro.magnum.RepoDefaults$.inline$genImpl(RepoDefaults.scala:39)
```

My current workaround:
```scala
given scala.reflect.ClassTag[Null] = new scala.reflect.ClassTag[Null] { def runtimeClass = classOf[Null] }
given DbCodec[Null] with {
  val cols = IArray(java.sql.Types.NULL)
  def readSingle(rs: java.sql.ResultSet, pos: Int) = null
  def writeSingle(a: Null, ps: java.sql.PreparedStatement, pos: Int) = ()
  def queryRepr = "NULL"
}
```

Is this expected or am I missing something in the setup?

Using scala 3.4.1 and magnum 1.1.1.

### LINKED ISSUE #24: DbCodec is not recursively applied
First of all, I am not a scala expert so it might be I am missing something obvious here.

I assumed the following would work (embedding values in entities)

```
@Table(H2DbType, SqlNameMapper.CamelToSnakeCase)
case class Company(
    name: String,
    address: Address,
) derives DbCodec

case class Address(
    street: String,
    city: String,
    zipCode: String,
    country: String
) derives DbCodec

object repo extends Repo[Company, Company, String]

transact(cp):
    repo.insert(company)
```

but the address does not get "expanded" in the geneerated insert statement

```
Column "ADDRESS" not found; SQL statement:
INSERT INTO company (name, address) VALUES (?, ?, ?, ?, ?, ?, ?)
```

again - if I am missing something obvious, I apologize, in that case consider this issue a suggestion for documentation

### PR DESCRIPTION
**Pull request by AugustNagro**
Closes #24

### CODE REVIEW

**Comment by alwins0n** [comment]
After re-reading it on the projects main page, I wanted to add one minor correction: Database DO support nested/embedded structures such as postgres composite type, so it's wrong to state that they don't or only support flat structures.

e.g. https://www.postgresql.org/docs/current/sql-createtype.html

**Comment by AugustNagro** [comment]
That's a good point.. I will re-word.

For Postgres, it appears that the JDBC driver does not support user-defined types https://github.com/pgjdbc/pgjdbc/issues/641

However, I WOULD support this feature, user-defined type support, for databases that support them, IF the official JDBC driver also gains support.

As it stands, there is a work-around one could use for UDTs in Postgres + Magnum. For the embedded class, you can define a custom DBCodec that grabs the column as a Pgobject , then does some custom deserialization (have not tested):

```
  given EmbeddedAddressCodec: DbCodec[Address] with
    def queryRepr: String = "?"
    val cols: IArray[Int] = IArray(Types.JAVA_OBJECT)
    def readSingle(resultSet: ResultSet, pos: Int): Address =
      val obj = resultSet.getObject(pos, classOf[PGobject])
      customDeser(obj.getValue)
    def writeSingle(entity: Address, ps: PreparedStatement, pos: Int): Unit =
      val res = customSer(entity)
      ps.setObject(pos, res)
 ```

You could then even make it generic.

**Comment by AugustNagro** [comment]
> You could then even make it generic.

Maybe by defining 

trait UdtDbCodec[A] extends DbCodec[A]

**Comment by alwins0n** [comment]
Thanks for the hint. I will fiddle a little with your library. Maybe I can extend the functionality to my requirements. After all I should always be able to supply a custom DbCodec right?

**Pull request merged**
